<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail junk_report plugin         |
 |                                                                       |
 | Copyright (C) IRCF                                                    |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+
*/

$labels['title'] = 'Junk Report';
$labels['description'] = 'The Junk Report allows you to receive regularly the list of spam messages in your mailbox.';
$labels['frequency'] = 'Frequency';
$labels['never'] = 'Never';
$labels['daily'] = 'Daily';
$labels['weekly'] = 'Weekly';
$labels['monthly'] = 'Monthly';
$labels['maxlength'] = 'Number of messages to display';
$labels['save'] = 'Save';
$labels['save_done'] = 'Settings saved';
$labels['not_junk'] = 'Mark as not junk';
$labels['auth_failed'] = 'Authentication failed, the link used has expired.';
$labels['not_junk_done'] = 'This message has been marked as not junk and moved to your inbox.';
$labels['cron_done'] = 'Messages sent';
