<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail junk_report plugin         |
 |                                                                       |
 | Copyright (C) IRCF                                                    |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+
*/

$labels['title'] = 'Rapport de pourriels';
$labels['description'] = 'Le rapport de pourriels vous permet de recevoir régulièrement la liste des pourriels dans votre boite mail.';
$labels['frequency'] = 'Fréquence';
$labels['never'] = 'Jamais';
$labels['daily'] = 'Chaque jour';
$labels['weekly'] = 'Chaque semaine';
$labels['monthly'] = 'Chaque mois';
$labels['maxlength'] = 'Nombre de messages à afficher';
$labels['save'] = 'Enregistrer';
$labels['save_done'] = 'Réglages enregistrés';
$labels['not_junk'] = 'Marquer en non pourriel';
$labels['auth_failed'] = "L'authentification a échouée, le lien utilisé n'est plus valide.";
$labels['not_junk_done'] = 'Ce message a été marqué en non pourriel et remis dans votre boite de réception.';
$labels['cron_done'] = 'Rapports envoyés';
